version: "3.8"

services:
  synthetic-text-agents:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DRY_RUN=true
      - FEATURE_LLM_QA=false
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add monitoring
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup
    restart: unless-stopped

networks:
  default:
    name: synthetic-text-agents-network
