# Feature Matrix Configuration
#
# Defines:
# - Plugin activation rules
# - Conflict resolution
# - Priority ordering
# - Canary rollout percentages
#
# Phase 2B Step 3: Plugin Integration

version: "1.0.0"
updated: "2025-10-08"

# ============================================================================
# Feedback Loop Configuration
# ============================================================================

feedback_loop:
  enabled: false # Default OFF (Feature Flag: FEATURE_FEEDBACK_LOOP_ENABLED)
  canary_percentage: 10 # 10% of requests when enabled
  auto_adjustment: false # Auto-adjust thresholds (Feature Flag: FEATURE_FEEDBACK_AUTO_ADJUSTMENT)
  drift_threshold: 0.15 # 15% drift triggers feedback loop
  baseline_tag: "integration-base"

# ============================================================================
# Plugin Registry Configuration
# ============================================================================

plugin_registry:
  enabled: false # Default OFF (Feature Flag: FEATURE_PLUGIN_REGISTRY_ENABLED)
  max_concurrent_plugins: 1 # Run only 1 plugin at a time initially
  auto_registration: false # Manual registration only
  priority_order: # Execution order (low to high)
    - rule_based # Always first (baseline)
    - evidence_aligner # Phase 2+
    - hybrid_search # Phase 3+ (canary)
    - multi_view_embedding # Phase 4+ (experimental)
    - ragas_eval # Phase 4+ (experimental)

# ============================================================================
# Advanced Quality Checkers (Plugin Definitions)
# ============================================================================

# Rule-Based Checker (Baseline - Always Active)
rule_based_checker:
  name: "rule-based-checker"
  enabled: true # Always ON
  phase: "Phase 1"
  priority: 1
  conflicts: [] # No conflicts
  dependencies: []

# Evidence Aligner (Phase 2+)
evidence_aligner:
  name: "evidence-aligner"
  enabled: true # Always ON in Phase 2+
  phase: "Phase 2"
  priority: 2
  conflicts: []
  dependencies: []

# Hybrid Search Checker (Phase 3 - Canary)
hybrid_search_checker:
  name: "hybrid-search-checker"
  enabled: false # OFF by default (Feature Flag: FEATURE_QUALITY_HYBRID_SEARCH)
  phase: "Phase 3"
  priority: 3
  canary_percentage: 10 # 10% canary when enabled
  conflicts: []
  dependencies: ["evidence_aligner"]

# Multi-View Embedding (Phase 4 - Experimental)
multi_view_embedding:
  name: "multi-view-embedding"
  enabled: false # OFF by default (Feature Flag: FEATURE_QUALITY_MULTIVIEW_EMBEDDING)
  phase: "Phase 4"
  priority: 4
  conflicts: ["query_side_embedding"] # Cannot run both at same time
  dependencies: ["evidence_aligner"]
  cost_per_qa: 0.005 # USD per QA pair
  max_budget: 1.0 # USD max total cost

# Query-Side Embedding (Phase 4 - Experimental)
query_side_embedding:
  name: "query-side-embedding"
  enabled: false # OFF by default (Feature Flag: FEATURE_QUALITY_QUERYSIDE_EMBEDDING)
  phase: "Phase 4"
  priority: 4
  conflicts: ["multi_view_embedding"] # Cannot run both at same time
  dependencies: ["evidence_aligner"]
  cost_per_qa: 0.003 # USD per QA pair
  max_budget: 1.0 # USD max total cost

# Translation-Based Embedding (Phase 4 - Experimental)
translation_embedding:
  name: "translation-embedding"
  enabled: false # OFF by default (Feature Flag: FEATURE_QUALITY_TRANSLATION_EMBEDDING)
  phase: "Phase 4"
  priority: 5
  conflicts: []
  dependencies: []
  cost_per_qa: 0.002 # USD per QA pair
  max_budget: 0.5 # USD max total cost

# Ragas Evaluation (Phase 4 - Experimental)
ragas_eval:
  name: "ragas-eval"
  enabled: false # OFF by default (Feature Flag: FEATURE_QUALITY_RAGAS_EVAL)
  phase: "Phase 4"
  priority: 6
  conflicts: []
  dependencies: ["evidence_aligner"]
  cost_per_qa: 0.01 # USD per QA pair (expensive)
  max_budget: 2.0 # USD max total cost

# ============================================================================
# Conflict Resolution Rules
# ============================================================================

conflict_resolution:
  # If multiple conflicting plugins are enabled, use this strategy
  strategy: "priority" # Options: "priority", "canary", "manual"

  # Priority-based: Higher priority wins
  # Canary-based: Random selection based on canary percentage
  # Manual: Require explicit selection

# ============================================================================
# Safety Limits
# ============================================================================

safety_limits:
  # Max total cost per run (USD)
  max_total_cost: 5.0

  # Max latency per checker (ms)
  max_latency_ms: 5000

  # Max error rate (0-1)
  max_error_rate: 0.1

  # Auto-disable if limits exceeded
  auto_disable_on_breach: true

# ============================================================================
# Rollback Configuration
# ============================================================================

rollback:
  # Auto-rollback if quality degrades
  auto_rollback_enabled: true

  # Degradation threshold (compared to baseline)
  degradation_threshold: 0.1 # 10% degradation triggers rollback

  # Baseline tag for comparison
  baseline_tag: "integration-base"
# ============================================================================
# Notes
# ============================================================================

# Feature Flags:
# - FEATURE_FEEDBACK_LOOP_ENABLED (default: false)
# - FEATURE_FEEDBACK_AUTO_ADJUSTMENT (default: false)
# - FEATURE_PLUGIN_REGISTRY_ENABLED (default: false)
# - FEATURE_QUALITY_HYBRID_SEARCH (default: false)
# - FEATURE_QUALITY_MULTIVIEW_EMBEDDING (default: false)
# - FEATURE_QUALITY_QUERYSIDE_EMBEDDING (default: false)
# - FEATURE_QUALITY_TRANSLATION_EMBEDDING (default: false)
# - FEATURE_QUALITY_RAGAS_EVAL (default: false)

# Usage:
# 1. Enable feature flags via environment variables
# 2. Start with canary percentages
# 3. Monitor metrics drift
# 4. Gradually increase canary percentage
# 5. Full rollout when stable

# Governance Integration:
# - All plugin activations logged to governance.jsonl
# - Gate D (Budget) monitors cost limits
# - Gate C (Stability) monitors quality degradation
# - Gate B (Autonomy) prevents infinite feedback loops
